---
- intf_name: Gi0/1
  desc: Connected to Core1 Switch
  speed: 100
  duplex: Full

- intf_name: Gi0/2
  desc: Connected to Core2 Switch
  speed: 100
  duplex: Full

- intf_name: Gi0/3
  desc: Connected to Core3 Switch
  speed: 100
  duplex: Full 